# StyleTTS2 Configuration File

# Model Architecture
model:
  hidden_dim: 256
  n_layers: 4
  n_heads: 2
  n_mels: 80
  reduction_factor: 1
  max_text_length: 500
  
# Audio Settings
audio:
  sampling_rate: 22050
  hop_length: 256
  win_length: 1024
  n_fft: 1024
  mel_fmin: 0
  mel_fmax: 8000
  
# Training Settings (for reference)
training:
  batch_size: 32
  learning_rate: 0.0001
  max_epochs: 1000
  warmup_steps: 1000
  checkpoint_interval: 1000
  
# Text Processing
text:
  cleaner: 'english_cleaners'
  add_blank: true
  normalize: true
  
# Speaker Settings
speaker:
  n_speakers: 1
  speaker_embedding_dim: 256
  
# Optimization
optimization:
  fp16: true
  grad_clip: 1.0
  
# Logging
logging:
  log_interval: 100
  eval_interval: 1000
  save_interval: 1000
  
# Security Settings
security:
  watermark_strength: 0.0001
  require_metadata: true
  max_generation_length: 1000  # maximum text length for generation
  log_all_operations: true